# ComfyUI Docker Compose File v1.0.1 by John Aldred
# http://www.johnaldred.com
# http://github.com/kaouthia

services:
  comfyui:
    build:
      dockerfile: Dockerfile
    image: comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    user: "1000:1000"
    volumes:
      # persist your models
      - /home/thomas/comfyui/models:/app/ComfyUI/models:r

      # persist your output images:
      - //home/thomas/comfyui/output:/app/ComfyUI/output

      # persist all your settings & extra nodes:
      - /home/thomas/comfyui/settings:/app/ComfyUI/user/default:rw

      # persist just your saved flows (overrides the workflows/ in default):
      - /home/thomas/comfyui/flows:/app/ComfyUI/user/default/workflows:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped